### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by nicklasb** [forms-angular/fng-reports#1]
Hi,

Do you have an example that demonstrates the library in action?

**Comment by mchapman** [comment]
Hi.  Thanks for your interest in forms-angular.

The two places to look for examples are at http://www.forms-angular.org/#/plugins#reports (probably the neatest examples it points to are [these](http://www.forms-angular.org/#/analyse/g_conditional_field/breakdownbysex) [two](http://www.forms-angular.org/#/analyse/g_conditional_field/totalforonesex)) and the applicant you can generate using the [generator](https://www.npmjs.com/package/generator-fng).

If you need any further pointers don't hesitate to ask.
